### ISSUE TITLE
perf data

### ISSUE THREAD

**Issue by invitu** [AndreySV/check_modbus#10]
Hi Andrey

Do you plan to include perf data support ?

Best regards

**Comment by AndreySV** [comment]
On 18 Sep, invitu wrote:
> Hi Andrey
> 
> Do you plan to include perf data support ?
> 
> Best regards

Hi, if I recall correctly, check_modbus supports perf data already.
See man page, parameters --perf_min, --pref_max, --perf_label, --perf_data.

-- 
Best regards,
Andrey Skvortsov

Secure e-mail with gnupg: See http://www.gnupg.org/
PGP Key ID: 0x57A3AEAD

**Comment by invitu** [comment]
of course, thanks for pointing that
