### ISSUE TITLE
adress parameter is shift by one

### ISSUE THREAD

**Issue by invitu** [AndreySV/check_modbus#11]
Hi Andrey

When I launch check_modbus with address 5636, it seems to shift to 5635

./check_modbus -H 192.168.0.2 -a 5636 -f3 -v

output : 
---------------------------------------------
Settings:
ip:          192.168.0.2
port:        502

verbosity:   1
device:      1
address:     5635

What do you think ?

Best regards

**Comment by AndreySV** [comment]
On 18 Sep, invitu wrote:
> Hi Andrey
> 
> When I launch check_modbus with address 5636, it seems to shift to 5635
> 
> ./check_modbus -H 192.168.0.2 -a 5636 -f3 -v
> 
> output : 
> ---------------------------------------------
> Settings:
> ip:          192.168.0.2
> port:        502
> 
> verbosity:   1
> device:      1
> address:     5635
> 
> What do you think ?
>

I think, this is ok. In device manuals sometimes modbus registers start from 0,
sometimes from 1. Register and bit address in check_modbus start
from 1. Take this into account, when you set value to --address parameter.

Thanks for mentioning this, I've expanded --address parameter's
description in the man page.

-- 
Best regards,
Andrey Skvortsov

Secure e-mail with gnupg: See http://www.gnupg.org/
PGP Key ID: 0x57A3AEAD

**Comment by invitu** [comment]
I'm fine with that
best regards
