### ISSUE TITLE
need calculating support

### ISSUE THREAD

**Issue by invitu** [AndreySV/check_modbus#12]
Hi Andrey

This is a feature request more than an issue.

modbus device often reply with raw values that need to be computed in order to have human readable values or to have value in a custom unit (for example pressure could be in bars, Pa ...etc).

I saw a similar feature in https://exchange.nagios.org/directory/Plugins/Hardware/Environmental/check_snmp_temperature/details

the parameter -i allows to divide the raw value and to add a unit symbol if needed...

I think it would be great to add that feature to check_modbus

Best Regards

**Comment by AndreySV** [comment]
On 18 Sep, invitu wrote:
> Hi Andrey
> 
> This is a feature request more than an issue.
> 
> modbus device often reply with raw values that need to be computed in order to have human readable values or to have value in a custom unit (for example pressure could be in bars, Pa ...etc).
> 
> I saw a similar feature in https://exchange.nagios.org/directory/Plugins/Hardware/Environmental/check_snmp_temperature/details
> 
> the parameter -i allows to divide the raw value and to add a unit symbol if needed...
> 
> I think it would be great to add that feature to check_modbus

check_modbus supports only simple calculations, like gain*x + offset.
Look at --gain and --offset parameters in the man page.
You can divide the raw value using there parameters. 
If you need more complex calculation, I recommend you to implement
external wrapper around check_modbus.

About unit symbol. Nagios plugin development guideline
( https://nagios-plugins.org/doc/guidelines.html#AEN200 )describes only
limited list of UOM:

UOM (unit of measurement) is one of:

    no unit specified - assume a number (int or float) of things (eg, users, processes, load averages)

    s - seconds (also us, ms)

    % - percentage

    B - bytes (also KB, MB, TB)

    c - a continous counter (such as bytes transmitted on an interface)


In automation field, where modbus devices are used usually, register
values UOM can be almost any physical quantity.
Therefore I decided to just leave this field empty.


-- 
Best regards,
Andrey Skvortsov

Secure e-mail with gnupg: See http://www.gnupg.org/
PGP Key ID: 0x57A3AEAD

**Comment by invitu** [comment]
once again, you pointed me right way
thanks and have a good weekend
