### ISSUE TITLE
Any chance to get option to scale output?

### ISSUE THREAD

**Issue by swapper82** [AndreySV/check_modbus#23]
This is a great plugin, but it would be even better if it could scale the output with a option.

**Comment by AndreySV** [comment]
Doesn't gain and offset fit your needs?
https://github.com/AndreySV/check_modbus/blob/master/src/check_modbus.1#L243

**Comment by swapper82** [comment]
Oh, that works like a charm.
But it does not show as an option on the command prompt check_modbus --help 
So not that easy to find.
or is it just me ?

**Comment by AndreySV** [comment]
good catch, I'll fix help message.
