### ISSUE TITLE
I'm getting a syntax error leading to no perf data

### ISSUE THREAD

**Issue by ljblom** [AndreySV/check_modbus#24]
Hello, I'm currently having a an issue with my check_modbus services. I've been running the service since June, and everything was working great, until early December. The checks are coming back successful, but the performance data stopped logging due to a syntax error in the response to the check, ex : Ah=8.39843750000000000000 | 8.39843750000000000000 >= 15 : syntax error: invalid arithmetic operator (error token is ".39843750000000000000 <= 14 || 8.39843750000000000000 >= 15 ")]

I opened a post in the nagios forum, and they suggested contacting you. Any help would be greatly appreciated!

**Comment by AndreySV** [comment]
On 18-01-24 18:52, ljblom wrote:
> Hello, I'm currently having a an issue with my check_modbus services. I've been running the service since June, and everything was working great, until early December. The checks are coming back successful, but the performance data stopped logging due to a syntax error in the response to the check, ex : Ah=8.39843750000000000000 | 8.39843750000000000000 >= 15 : syntax error: invalid arithmetic operator (error token is ".39843750000000000000 <= 14 || 8.39843750000000000000 >= 15 ")]
> 
> I opened a post in the nagios forum, and they suggested contacting you. Any help would be greatly appreciated!

Is it because something changed in the way Nagios handles performance data?
Could you post exact command line for check_modbus?


-- 
Best regards,
Andrey Skvortsov

**Comment by ljblom** [comment]
Hi AndreySV, we got it figured out... Not sure what cause the perfdata to be logged, and then not logged without any corresponding config changes though:/ The issue was that the -l and -u checks look for integers, and the check was sending a float to the checks. So, we just made the the value that's checked an integer by multiplying both the value and threshold by 10 (so we could still get 1/10 resolution on the thresh hold comparisons). That did it... Perf data is logging again.

**Comment by AndreySV** [comment]
Hi,
what do you mean by '-l and -u'? check_modbus doesn't have such options. 

BTW, do you use check_modbus's --gain and --offset options to get floats and not external wrapper, because I found your [post](https://support.nagios.com/forum/viewtopic.php?f=16&t=43339) on nagios support forum about. You don't need any wrapper to do scalling, this functional is available in check_modbus out of the box.

See [man page](https://github.com/AndreySV/check_modbus/blob/master/src/check_modbus.1#L246).

**Comment by ljblom** [comment]
Hi AndreySV, thanks for the reply and tip about scaling in check_modbus. Sorry for the confusion, I'm using a wrapper for the check to be able to have upper and lower limits. We're testing a new charge controller and want to be notified when voltage, current, or temp wanders outside a certain range. Basically, I'm testing the modbus wrapper checks as well. 

So, the error was in the wrapper, not in check_modbus.

**Comment by AndreySV** [comment]
Hi,  
you don't need any wrapper to be able to have upper and lower limits. check_modbus does support nagios format of threshold and ranges. See Nagios [documentation](https://nagios-plugins.org/doc/guidelines.html#THRESHOLDFORMAT).
