### ISSUE TITLE
Support to handle negative values

### ISSUE THREAD

**Issue by swapper82** [AndreySV/check_modbus#25]
Hi, i dont know if this is a supported function already and im doing it wrong or if its not supported.
Apologies if that the case.

Im using the check command to monitor outside temperature, mostly to get the performance graphs.
But when the temperatures goes below zero it seems that its got problems handling the negative values.

if i omit the -w and -c parameters to get the check to ignore warning and cirtical (only performance data)
Then i get an return code "UNKNOWN"
```
[master01 custom]# ./check_modbus2 --ip=OURIP -d 1 -a 72 -f 4 -F 1 -i -P -L 'C' -t 3 --gain 0.1
UNKNOWN: -8.300000              |'C'=-8.300000;;;;
```
if i add the -w parameter the check returns and error.

```
[master01 custom]# ./check_modbus2 --ip=OURIP  -d 1 -a 72 -f 4 -F 1 -i -P -L 'C' -t 3 --gain 0.1 -w '-10'
command_line.c:587:parse_command_line(): can't parse warning range -10
```

Any hints?

**Comment by AndreySV** [comment]
On 18-02-28 08:38, swapper82 wrote:
> Hi, i dont know if this is a supported function already and im doing it wrong or if its not supported.
> Apologies if that the case.
> 
> Im using the check command to monitor outside temperature, mostly to get the performance graphs.
> But when the temperatures goes below zero it seems that its got problems handling the negative values.
> 
> if i omit the -w and -c parameters to get the check to ignore warning and cirtical (only performance data)
> Then i get an return code "UNKNOWN"
> ```
> [master01 custom]# ./check_modbus2 --ip=OURIP -d 1 -a 72 -f 4 -F 1 -i -P -L 'C' -t 3 --gain 0.1
> UNKNOWN: -8.300000              |'C'=-8.300000;;;;
> ```
> if i add the -w parameter the check returns and error.
> 
> ```
> [master01 custom]# ./check_modbus2 --ip=10.249.97.143 -d 1 -a 72 -f 4 -F 1 -i -P -L 'C' -t 3 --gain 0.1 -w '-10'
> command_line.c:587:parse_command_line(): can't parse warning range -10
> ```
> 
> Any hints?

You have problem in your warning range. See Nagios documentation.
https://nagios-plugins.org/doc/guidelines.html#THRESHOLDFORMAT

In your range '-10', you omitted start point. By default 0 is used
according to the Nagios documentation. As a result your range looks
like this [0; -10]. That is wrong.

I'm not sure what you are want to achieve with warning range. Here are
some examples:
1) Warning if temperature goes below -10C:  -w '@~:-10'
2) Warning if temperature goes higher -10C: -w '-10:'


-- 
Best regards,
Andrey Skvortsov
