### ISSUE TITLE
Timeout value

### ISSUE THREAD

**Issue by swapper82** [AndreySV/check_modbus#26]
Hi, 
im having some issue when using check_modbus as a host up/down check.
When the host goes down the plugin seems to have a very long timeout (more then 60 sec).
Is there a way to adjust the timeout when the IP of device cant be reached?

**Comment by AndreySV** [comment]
AFAIK there is no way to set socket specific connect timeout. It depends on the operating system you use. IIRC on GNU/Linux it's controlled by net.ipv4.tcp_syn_retries. But this is system-wide setting and will apply to all applications.
